// Code generated by "sumgen"; DO NOT EDIT.

package ast

func (F *File) node()      { panic("default implementation") }
func (H *Header) node()    { panic("default implementation") }
func (D *Directive) node() { panic("default implementation") }
func (L *List) node()      { panic("default implementation") }
func (L ListItem) node()   { panic("default implementation") }
func (P *Paragraph) node() { panic("default implementation") }
func (T Text) node()       { panic("default implementation") }
func (H *Header) stmt()    { panic("default implementation") }
func (D *Directive) stmt() { panic("default implementation") }
func (L *List) stmt()      { panic("default implementation") }
func (P *Paragraph) stmt() { panic("default implementation") }
func (C *Citation) node()  { panic("default implementation") }
func (C *Citation) stmt()  { panic("default implementation") }
