// Code generated by "sumgen"; DO NOT EDIT.

package ast

func (_ *Directive) node() { panic("default implementation") }
func (_ *File) node()      { panic("default implementation") }
func (_ *Header) node()    { panic("default implementation") }
func (_ *List) node()      { panic("default implementation") }
func (_ ListItem) node()   { panic("default implementation") }
func (_ *Paragraph) node() { panic("default implementation") }
func (_ Text) node()       { panic("default implementation") }
func (_ *Citation) node()  { panic("default implementation") }
func (_ *Citation) stmt()  { panic("default implementation") }
func (_ *Directive) stmt() { panic("default implementation") }
func (_ *Header) stmt()    { panic("default implementation") }
func (_ *List) stmt()      { panic("default implementation") }
func (_ *Paragraph) stmt() { panic("default implementation") }
